db.hoteles.insertMany([
  // Hoteles en Colombia
  { nombreHotel: "Hotel Movich Cartagena", ubicacion: "Cartagena, Colombia", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Hotel boutique con vistas panorámicas de la ciudad amurallada.", capacidadPersonas: 150, areaTotalHotelM2: 12000, tarifaPromedioEstadiaUSD: 200, numeroPisos: 5, tamanoHabitacionesM2: 35, ingresosMensualesUSD: 450000 },
  { nombreHotel: "Sofitel Legend Santa Clara", ubicacion: "Cartagena, Colombia", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Antiguo convento con una mezcla de arquitectura colonial y moderna.", capacidadPersonas: 250, areaTotalHotelM2: 15000, tarifaPromedioEstadiaUSD: 350, numeroPisos: 6, tamanoHabitacionesM2: 40, ingresosMensualesUSD: 600000 },
  { nombreHotel: "Four Seasons Hotel", ubicacion: "Bogotá, Colombia", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Hotel contemporáneo en el corazón de la zona rosa de Bogotá.", capacidadPersonas: 180, areaTotalHotelM2: 10000, tarifaPromedioEstadiaUSD: 280, numeroPisos: 5, tamanoHabitacionesM2: 38, ingresosMensualesUSD: 500000 },
  { nombreHotel: "Hotel Dann Carlton Medellin", ubicacion: "Medellín, Colombia", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Elegante hotel con piscina en el área financiera de Medellín.", capacidadPersonas: 300, areaTotalHotelM2: 18000, tarifaPromedioEstadiaUSD: 180, numeroPisos: 7, tamanoHabitacionesM2: 42, ingresosMensualesUSD: 650000 },
  { nombreHotel: "Hotel Estelar La Fontana", ubicacion: "Bogotá, Colombia", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Ubicado en una zona exclusiva con fácil acceso a centros comerciales.", capacidadPersonas: 350, areaTotalHotelM2: 20000, tarifaPromedioEstadiaUSD: 230, numeroPisos: 8, tamanoHabitacionesM2: 45, ingresosMensualesUSD: 700000 },
  { nombreHotel: "Intercontinental Cali", ubicacion: "Cali, Colombia", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Hotel clásico en el centro de la ciudad con servicios de primera clase.", capacidadPersonas: 250, areaTotalHotelM2: 15000, tarifaPromedioEstadiaUSD: 250, numeroPisos: 6, tamanoHabitacionesM2: 40, ingresosMensualesUSD: 550000 },
  { nombreHotel: "Hotel Las Islas", ubicacion: "Islas del Rosario, Colombia", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Hotel ecológico con bungalows privados y acceso directo al mar.", capacidadPersonas: 200, areaTotalHotelM2: 18000, tarifaPromedioEstadiaUSD: 400, numeroPisos: 2, tamanoHabitacionesM2: 50, ingresosMensualesUSD: 600000 },
  { nombreHotel: "Hotel Hilton Bogotá", ubicacion: "Bogotá, Colombia", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Hotel moderno con gimnasio, piscina y restaurantes gourmet.", capacidadPersonas: 280, areaTotalHotelM2: 14000, tarifaPromedioEstadiaUSD: 300, numeroPisos: 9, tamanoHabitacionesM2: 40, ingresosMensualesUSD: 750000 },
  { nombreHotel: "Hotel Casa San Agustín", ubicacion: "Cartagena, Colombia", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Lujoso hotel colonial con una mezcla de modernidad y antigüedad.", capacidadPersonas: 120, areaTotalHotelM2: 8000, tarifaPromedioEstadiaUSD: 350, numeroPisos: 3, tamanoHabitacionesM2: 36, ingresosMensualesUSD: 500000 },
  { nombreHotel: "Hotel Grand Hyatt Bogotá", ubicacion: "Bogotá, Colombia", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Imponente hotel con vistas panorámicas de la ciudad y spa de lujo.", capacidadPersonas: 350, areaTotalHotelM2: 25000, tarifaPromedioEstadiaUSD: 280, numeroPisos: 11, tamanoHabitacionesM2: 45, ingresosMensualesUSD: 800000 },
  // Hoteles en Brasil
  { nombreHotel: "Tivoli Mofarrej", ubicacion: "Sao Paulo, Brasil", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Hotel de lujo con vistas al parque Trianon y la Avenida Paulista.", capacidadPersonas: 400, areaTotalHotelM2: 22000, tarifaPromedioEstadiaUSD: 320, numeroPisos: 10, tamanoHabitacionesM2: 50, ingresosMensualesUSD: 850000 },
  { nombreHotel: "Copacabana Palace", ubicacion: "Río de Janeiro, Brasil", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Icónico hotel frente a la playa de Copacabana.", capacidadPersonas: 500, areaTotalHotelM2: 30000, tarifaPromedioEstadiaUSD: 450, numeroPisos: 12, tamanoHabitacionesM2: 55, ingresosMensualesUSD: 1200000 },
  { nombreHotel: "Fasano Hotel", ubicacion: "Río de Janeiro, Brasil", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Hotel contemporáneo con vistas al mar y diseño minimalista.", capacidadPersonas: 200, areaTotalHotelM2: 16000, tarifaPromedioEstadiaUSD: 400, numeroPisos: 6, tamanoHabitacionesM2: 50, ingresosMensualesUSD: 750000 },
  { nombreHotel: "Grand Hyatt Río", ubicacion: "Río de Janeiro, Brasil", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Lujoso hotel junto a la playa de Barra da Tijuca.", capacidadPersonas: 600, areaTotalHotelM2: 40000, tarifaPromedioEstadiaUSD: 350, numeroPisos: 10, tamanoHabitacionesM2: 60, ingresosMensualesUSD: 1400000 },
  { nombreHotel: "Sheraton Grand Río", ubicacion: "Río de Janeiro, Brasil", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Único hotel de lujo frente a la playa en el área de Leblon.", capacidadPersonas: 700, areaTotalHotelM2: 50000, tarifaPromedioEstadiaUSD: 370, numeroPisos: 13, tamanoHabitacionesM2: 58, ingresosMensualesUSD: 1600000 },
  { nombreHotel: "Belmond Hotel das Cataratas", ubicacion: "Foz de Iguazú, Brasil", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Hotel con impresionantes vistas a las Cataratas del Iguazú.", capacidadPersonas: 400, areaTotalHotelM2: 28000, tarifaPromedioEstadiaUSD: 400, numeroPisos: 7, tamanoHabitacionesM2: 50, ingresosMensualesUSD: 1300000 },
  { nombreHotel: "Emiliano Hotel", ubicacion: "Sao Paulo, Brasil", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Elegante hotel boutique en la exclusiva Avenida Oscar Freire.", capacidadPersonas: 120, areaTotalHotelM2: 10000, tarifaPromedioEstadiaUSD: 380, numeroPisos: 6, tamanoHabitacionesM2: 40, ingresosMensualesUSD: 600000 },
  { nombreHotel: "Hotel Unique", ubicacion: "Sao Paulo, Brasil", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Hotel con arquitectura futurista y diseño moderno en Sao Paulo.", capacidadPersonas: 350, areaTotalHotelM2: 30000, tarifaPromedioEstadiaUSD: 420, numeroPisos: 8, tamanoHabitacionesM2: 50, ingresosMensualesUSD: 1200000 },
  { nombreHotel: "Hilton Sao Paulo Morumbi", ubicacion: "Sao Paulo, Brasil", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Hotel de negocios con vistas al Puente Octavio Frias de Oliveira.", capacidadPersonas: 400, areaTotalHotelM2: 25000, tarifaPromedioEstadiaUSD: 350, numeroPisos: 11, tamanoHabitacionesM2: 45, ingresosMensualesUSD: 1100000 },
  {nombreHotel: "Palácio Tangará", ubicacion: "Sao Paulo, Brasil", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Exclusivo hotel rodeado por un parque tropical en Sao Paulo.", capacidadPersonas: 280, areaTotalHotelM2: 22000, tarifaPromedioEstadiaUSD: 400, numeroPisos: 7, tamanoHabitacionesM2: 48, ingresosMensualesUSD: 950000 },
  // Hoteles en Panama
  { nombreHotel: "American Trade Hotel", ubicacion: "Ciudad de Panamá, Panamá", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Hotel boutique en el Casco Viejo con estilo colonial.", capacidadPersonas: 120, areaTotalHotelM2: 9000, tarifaPromedioEstadiaUSD: 300, numeroPisos: 5, tamanoHabitacionesM2: 35, ingresosMensualesUSD: 400000 },
  { nombreHotel: "Hilton Panamá", ubicacion: "Ciudad de Panamá, Panamá", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Moderno hotel con vistas al Océano Pacífico.", capacidadPersonas: 300, areaTotalHotelM2: 15000, tarifaPromedioEstadiaUSD: 280, numeroPisos: 10, tamanoHabitacionesM2: 42, ingresosMensualesUSD: 700000 },
  { nombreHotel: "JW Marriott Panamá", ubicacion: "Ciudad de Panamá, Panamá", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Imponente hotel con vistas panorámicas y piscina infinita.", capacidadPersonas: 400, areaTotalHotelM2: 25000, tarifaPromedioEstadiaUSD: 350, numeroPisos: 11, tamanoHabitacionesM2: 50, ingresosMensualesUSD: 1100000 },
  { nombreHotel: "Waldorf Astoria Panamá", ubicacion: "Ciudad de Panamá, Panamá", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Lujoso hotel con servicio de primera clase y spa.", capacidadPersonas: 250, areaTotalHotelM2: 16000, tarifaPromedioEstadiaUSD: 320, numeroPisos: 9, tamanoHabitacionesM2: 45, ingresosMensualesUSD: 800000 },
  { nombreHotel: "Intercontinental Miramar Panamá", ubicacion: "Ciudad de Panamá, Panamá", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Hotel con vistas al océano y un amplio centro de convenciones.", capacidadPersonas: 350, areaTotalHotelM2: 18000, tarifaPromedioEstadiaUSD: 290, numeroPisos: 12, tamanoHabitacionesM2: 40, ingresosMensualesUSD: 900000 },
  { nombreHotel: "The Westin Playa Bonita", ubicacion: "Playa Bonita, Panamá", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Resort de lujo frente al mar con amplias instalaciones.", capacidadPersonas: 500, areaTotalHotelM2: 35000, tarifaPromedioEstadiaUSD: 400, numeroPisos: 10, tamanoHabitacionesM2: 50, ingresosMensualesUSD: 1500000 },
  { nombreHotel: "Riu Plaza Panamá", ubicacion: "Ciudad de Panamá, Panamá", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Moderno hotel en el centro de la ciudad con vistas impresionantes.", capacidadPersonas: 450, areaTotalHotelM2: 30000, tarifaPromedioEstadiaUSD: 320, numeroPisos: 12, tamanoHabitacionesM2: 48, ingresosMensualesUSD: 1400000 },
  { nombreHotel: "Hotel Las Américas Golden Tower", ubicacion: "Ciudad de Panamá, Panamá", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Hotel con diseño futurista y lujosos servicios.", capacidadPersonas: 350, areaTotalHotelM2: 24000, tarifaPromedioEstadiaUSD: 350, numeroPisos: 11, tamanoHabitacionesM2: 50, ingresosMensualesUSD: 1000000 },
  { nombreHotel: "Hotel Bristol", ubicacion: "Ciudad de Panamá, Panamá", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Elegante hotel boutique con estilo clásico.", capacidadPersonas: 180, areaTotalHotelM2: 14000, tarifaPromedioEstadiaUSD: 280, numeroPisos: 8, tamanoHabitacionesM2: 42, ingresosMensualesUSD: 650000 },
  { nombreHotel: "Sortis Hotel", ubicacion: "Ciudad de Panamá, Panamá", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Hotel de lujo con casino y centro de entretenimiento.", capacidadPersonas: 500, areaTotalHotelM2: 32000, tarifaPromedioEstadiaUSD: 380, numeroPisos: 13, tamanoHabitacionesM2: 50, ingresosMensualesUSD: 1500000 },
  // Hoteles en Argentina
  { nombreHotel: "Alvear Palace Hotel", ubicacion: "Buenos Aires, Argentina", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Emblemático hotel de lujo en el barrio de Recoleta.", capacidadPersonas: 450, areaTotalHotelM2: 35000, tarifaPromedioEstadiaUSD: 500, numeroPisos: 10, tamanoHabitacionesM2: 60, ingresosMensualesUSD: 2000000 },
  { nombreHotel: "Four Seasons Hotel Buenos Aires", ubicacion: "Buenos Aires, Argentina", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Lujoso hotel con mezcla de diseño clásico y moderno.", capacidadPersonas: 350, areaTotalHotelM2: 30000, tarifaPromedioEstadiaUSD: 450, numeroPisos: 8, tamanoHabitacionesM2: 55, ingresosMensualesUSD: 1500000 },
  { nombreHotel: "Faena Hotel Buenos Aires", ubicacion: "Buenos Aires, Argentina", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Exclusivo hotel con diseño de Philippe Starck.", capacidadPersonas: 250, areaTotalHotelM2: 20000, tarifaPromedioEstadiaUSD: 420, numeroPisos: 7, tamanoHabitacionesM2: 50, ingresosMensualesUSD: 1000000 },
  { nombreHotel: "Hotel Madero", ubicacion: "Buenos Aires, Argentina", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Hotel moderno con amplias habitaciones y spa.", capacidadPersonas: 400, areaTotalHotelM2: 28000, tarifaPromedioEstadiaUSD: 400, numeroPisos: 9, tamanoHabitacionesM2: 48, ingresosMensualesUSD: 1300000 },
  { nombreHotel: "Park Hyatt Mendoza", ubicacion: "Mendoza, Argentina", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Elegante hotel con vistas a los Andes y un casino.", capacidadPersonas: 300, areaTotalHotelM2: 22000, tarifaPromedioEstadiaUSD: 350, numeroPisos: 6, tamanoHabitacionesM2: 45, ingresosMensualesUSD: 1100000 },
  { nombreHotel: "Llao Llao Resort", ubicacion: "Bariloche, Argentina", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Impresionante resort de montaña con vistas al lago y montañas.", capacidadPersonas: 500, areaTotalHotelM2: 40000, tarifaPromedioEstadiaUSD: 480, numeroPisos: 8, tamanoHabitacionesM2: 60, ingresosMensualesUSD: 1800000 },
  { nombreHotel: "Sheraton Buenos Aires", ubicacion: "Buenos Aires, Argentina", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Moderno hotel de lujo en el corazón de Buenos Aires.", capacidadPersonas: 450, areaTotalHotelM2: 30000, tarifaPromedioEstadiaUSD: 400, numeroPisos: 13, tamanoHabitacionesM2: 48, ingresosMensualesUSD: 1600000 },
  { nombreHotel: "Palacio Duhau Park Hyatt", ubicacion: "Buenos Aires, Argentina", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Exclusivo hotel con arquitectura histórica y jardines.", capacidadPersonas: 350, areaTotalHotelM2: 25000, tarifaPromedioEstadiaUSD: 460, numeroPisos: 8, tamanoHabitacionesM2: 55, ingresosMensualesUSD: 1400000 },
  { nombreHotel: "Alvear Art Hotel", ubicacion: "Buenos Aires, Argentina", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Hotel contemporáneo en el centro financiero de la ciudad.", capacidadPersonas: 280, areaTotalHotelM2: 18000, tarifaPromedioEstadiaUSD: 420, numeroPisos: 9, tamanoHabitacionesM2: 50, ingresosMensualesUSD: 1200000 },
  { nombreHotel: "Cavas Wine Lodge", ubicacion: "Mendoza, Argentina", clasificacion: "5 estrellas", categoria: "lujo", descripcion: "Exclusivo hotel en una bodega con vistas a los viñedos.", capacidadPersonas: 150, areaTotalHotelM2: 12000, tarifaPromedioEstadiaUSD: 500, numeroPisos: 5, tamanoHabitacionesM2: 55, ingresosMensualesUSD: 900000 },
])
db.hoteles.find({ ubicacion: { $eq: "Cartagena, Colombia" } });
db.hoteles.find({ capacidadPersonas: { $gt: 100 } });
db.hoteles.find({ tarifaPromedioEstadiaUSD: { $gte: 150 } });
db.hoteles.find({ numeroPisos: { $lt: 10 } });
db.hoteles.find({ tamanoHabitacionesM2: { $lte: 40 } });
db.hoteles.find({ clasificacion: { $ne: "3 estrellas" } });
db.hoteles.find({ categoria: { $in: ["lujo", "negocios", "turismo"] } });
db.hoteles.find({ tarifaPromedioEstadiaUSD: { $nin: [100, 120] } });
db.hoteles.find({ ubicacion: "Cartagena, Colombia", numeroPisos: { $gt: 3 } });
db.hoteles.deleteOne({ nombreHotel: "Sofitel Legend Santa Clara", ubicacion: "Cartagena, Colombia" });


