db.materias.insertMany([
  { nombreMateria: "Calculo Integral", codigoMateria: "MAT201", descripcion: "Calculo de integrales definidas e indefinidas y sus aplicaciones", creditos: 3, horasTeoricas: 4, horasPracticas: 1, profesor: "MG. Marcela Gomez", aula: "Aula 204", prerrequisitos: "Calculo Diferencial", promedioClasificacion: 4.6 },
  { nombreMateria: "Practica de Base de Datos", codigoMateria: "SIS303", descripcion: "Fundamentos de bases de datos relacionales y modelado de datos", creditos: 3, horasTeoricas: 3, horasPracticas: 2, profesor: "Ing. Sebastian Carrera", aula: "Lab 303", prerrequisitos: "Programacion II", promedioClasificacion: 4.6 },
  { nombreMateria: "Python", codigoMateria: "SIS202", descripcion: "Introduccion a la programacion con Python y sus aplicaciones", creditos: 3, horasTeoricas: 3, horasPracticas: 2, profesor: "Mg. Mauricio Lopez", aula: "Lab 205", prerrequisitos: "Programacion I", promedioClasificacion: 4.5 },
  { nombreMateria: "Simulacion", codigoMateria: "MAT503", descripcion: "Modelado matematico y simulacion de sistemas complejos", creditos: 3, horasTeoricas: 4, horasPracticas: 1, profesor: "Mg. Danny Cardenas", aula: "Aula 207", prerrequisitos: "Analisis Numerico", promedioClasificacion: 4.6 },
  { nombreMateria: "Construccion de Sistemas de Informacion", codigoMateria: "SIS404", descripcion: "Metodologias de desarrollo de software desde el analisis hasta la implementacion", creditos: 4, horasTeoricas: 3, horasPracticas: 2, profesor: "Ing. Fabian Parra", aula: "Lab 305", prerrequisitos: "Programacion II", promedioClasificacion: 4.8 },
  { nombreMateria: "Calculo Diferencial", codigoMateria: "MAT101", descripcion: "Fundamentos del calculo de una variable incluyendo limites, derivadas y aplicaciones", creditos: 3, horasTeoricas: 4, horasPracticas: 1, profesor: "Mg. Wilson Castro", aula: "Aula 101", prerrequisitos: "Ninguno", promedioClasificacion: 4.5 },
  { nombreMateria: "Programacion I", codigoMateria: "SIS102", descripcion: "Introduccion a la programacion con enfoque en estructuras basicas de control y datos", creditos: 3, horasTeoricas: 3, horasPracticas: 2, profesor: "Ing. Sebastian Carrera", aula: "Lab 203", prerrequisitos: "Ninguno", promedioClasificacion: 4.7 },
  { nombreMateria: "Algebra Lineal", codigoMateria: "MAT102", descripcion: "Estudio de matrices, determinantes, vectores, espacios vectoriales y sus aplicaciones", creditos: 3, horasTeoricas: 4, horasPracticas: 1, profesor: "Mg. Javier Villalba", aula: "Aula 102", prerrequisitos: "Calculo Diferencial", promedioClasificacion: 4.4 },
  { nombreMateria: "Fisica I", codigoMateria: "FIS101", descripcion: "Fundamentos de la mecanica clasica, incluyendo cinematica y dinamica de particulas", creditos: 4, horasTeoricas: 3, horasPracticas: 3, profesor: "Dr. Sandra Rojas", aula: "Lab 105", prerrequisitos: "Ninguno", promedioClasificacion: 4.6 },
  { nombreMateria: "Quimica General", codigoMateria: "QUI101", descripcion: "Estudio de la estructura atomica, enlaces quimicos y reacciones fundamentales", creditos: 3, horasTeoricas: 3, horasPracticas: 2, profesor: "Dr. Juan Torres", aula: "Lab 301", prerrequisitos: "Ninguno", promedioClasificacion: 4.3 },
  { nombreMateria: "Historia del Arte", codigoMateria: "HIS104", descripcion: "Introduccion a la evolucion del arte desde la antiguedad hasta la era moderna", creditos: 2, horasTeoricas: 2, horasPracticas: 0, profesor: "MG. Ana Gonzalez", aula: "Aula 304", prerrequisitos: "Ninguno", promedioClasificacion: 4.9 },
  { nombreMateria: "Etica Profesional", codigoMateria: "HUM201", descripcion: "Analisis de dilemas eticos en el contexto profesional y personal", creditos: 2, horasTeoricas: 2, horasPracticas: 0, profesor: "Dra. Maria Suarez", aula: "Aula 402", prerrequisitos: "Ninguno", promedioClasificacion: 4.8 },
  { nombreMateria: "Economia Basica", codigoMateria: "ECO101", descripcion: "Introduccion a los principios economicos fundamentales tanto micro como macro", creditos: 3, horasTeoricas: 3, horasPracticas: 1, profesor: "Dr. Pedro Gomez", aula: "Aula 503", prerrequisitos: "Ninguno", promedioClasificacion: 4.2 },
  { nombreMateria: "Programacion II", codigoMateria: "SIS202", descripcion: "Estructuras de datos avanzadas y principios de programacion orientada a objetos", creditos: 3, horasTeoricas: 3, horasPracticas: 2, profesor: "Ing. Andres Mendez", aula: "Lab 205", prerrequisitos: "Programacion I", promedioClasificacion: 4.5 },
  { nombreMateria: "Ecuaciones Diferenciales", codigoMateria: "MAT301", descripcion: "Solucion de ecuaciones diferenciales ordinarias y parciales", creditos: 3, horasTeoricas: 4, horasPracticas: 1, profesor: "Dr. Ricardo Ramirez", aula: "Aula 206", prerrequisitos: "Calculo Integral", promedioClasificacion: 4.7 },
  { nombreMateria: "Redes de Computadoras", codigoMateria: "SIS305", descripcion: "Principios de redes de computadoras, topologias y protocolos", creditos: 4, horasTeoricas: 3, horasPracticas: 3, profesor: "Ing. Gabriel Pardo", aula: "Lab 202", prerrequisitos: "Ninguno", promedioClasificacion: 4.5 },
  { nombreMateria: "Fisica II", codigoMateria: "FIS202", descripcion: "Electromagnetismo, circuitos y ondas", creditos: 4, horasTeoricas: 3, horasPracticas: 3, profesor: "Dra. Veronica Reyes", aula: "Lab 107", prerrequisitos: "Fisica I", promedioClasificacion: 4.4 },
  { nombreMateria: "Ingenieria de Software", codigoMateria: "SIS404", descripcion: "Metodologias de desarrollo de software desde el analisis hasta la implementacion", creditos: 4, horasTeoricas: 3, horasPracticas: 2, profesor: "Ing. Alberto Rivas", aula: "Lab 305", prerrequisitos: "Programacion II", promedioClasificacion: 4.8 },
  { nombreMateria: "Analisis Numerico", codigoMateria: "MAT401", descripcion: "Metodos numericos para la solucion de ecuaciones y problemas matematicos complejos", creditos: 3, horasTeoricas: 4, horasPracticas: 1, profesor: "Mg. Dany Cardenas", aula: "Aula 201", prerrequisitos: "Calculo Integral", promedioClasificacion: 4.3 },
  { nombreMateria: "Probabilidad y Estadistica", codigoMateria: "MAT402", descripcion: "Teoria de la probabilidad y estadistica aplicada", creditos: 3, horasTeoricas: 4, horasPracticas: 1, profesor: "Dr. Alejandra Zuletta", aula: "Aula 202", prerrequisitos: "Algebra Lineal", promedioClasificacion: 4.7 },
  { nombreMateria: "Derecho Informatico", codigoMateria: "DRE305", descripcion: "Aspectos legales relacionados con el uso de la informatica y la propiedad intelectual", creditos: 2, horasTeoricas: 2, horasPracticas: 0, profesor: "Abg. Lucia Herrera", aula: "Aula 404", prerrequisitos: "Ninguno", promedioClasificacion: 4.8 },
  { nombreMateria: "Inteligencia Artificial", codigoMateria: "SIS506", descripcion: "Tecnicas y algoritmos utilizados en la inteligencia artificial", creditos: 4, horasTeoricas: 3, horasPracticas: 2, profesor: "Ing. Camilo Vargas", aula: "Lab 302", prerrequisitos: "Redes Neuronales", promedioClasificacion: 4.9 },
  { nombreMateria: "Seguridad Informatica", codigoMateria: "SIS801", descripcion: "Estudio de tecnicas y herramientas para garantizar la seguridad de sistemas informaticos", creditos: 4, horasTeoricas: 3, horasPracticas: 2, profesor: "Ing. Sebastian Carrera", aula: "Lab 309", prerrequisitos: "Ninguno", promedioClasificacion: 4.9 },
  { nombreMateria: "Arquitectura de Software", codigoMateria: "SIS701", descripcion: "Principios y tecnicas para el diseño de software", creditos: 4, horasTeoricas: 3, horasPracticas: 2, profesor: "Ing. Monica Delgado", aula: "Lab 207", prerrequisitos: "Ingenieria de Software", promedioClasificacion: 4.8 },
  { nombreMateria: "Calculo Integral", codigoMateria: "MAT201", descripcion: "Calculo de integrales definidas e indefinidas y sus aplicaciones", creditos: 3, horasTeoricas: 4, horasPracticas: 1, profesor: "MG. Marcela Gomez", aula: "Aula 204", prerrequisitos: "Calculo Diferencial", promedioClasificacion: 4.6 },
  { nombreMateria: "Practica de Base de Datos", codigoMateria: "SIS303", descripcion: "Fundamentos de bases de datos relacionales y modelado de datos", creditos: 3, horasTeoricas: 3, horasPracticas: 2, profesor: "Ing. Sebastian Carrera", aula: "Lab 303", prerrequisitos: "Programacion II", promedioClasificacion: 4.6 },
  { nombreMateria: "Python", codigoMateria: "SIS202", descripcion: "Introduccion a la programacion con Python y sus aplicaciones", creditos: 3, horasTeoricas: 3, horasPracticas: 2, profesor: "Mg. Mauricio Lopez", aula: "Lab 205", prerrequisitos: "Programacion I", promedioClasificacion: 4.5 },
  { nombreMateria: "Simulacion", codigoMateria: "MAT503", descripcion: "Modelado matematico y simulacion de sistemas complejos", creditos: 3, horasTeoricas: 4, horasPracticas: 1, profesor: "Mg. Danny Cardenas", aula: "Aula 207", prerrequisitos: "Analisis Numerico", promedioClasificacion: 4.6 },
  { nombreMateria: "Construccion de Sistemas de Informacion", codigoMateria: "SIS404", descripcion: "Metodologias de desarrollo de software desde el analisis hasta la implementacion", creditos: 4, horasTeoricas: 3, horasPracticas: 2, profesor: "Ing. Fabian Parra", aula: "Lab 305", prerrequisitos: "Programacion II", promedioClasificacion: 4.8 },
  { nombreMateria: "Calculo Diferencial", codigoMateria: "MAT101", descripcion: "Fundamentos del calculo de una variable incluyendo limites derivadas y aplicaciones", creditos: 3, horasTeoricas: 4, horasPracticas: 1, profesor: "Mg. Wilson Castro", aula: "Aula 101", prerrequisitos: "Ninguno", promedioClasificacion: 4.5 },
  { nombreMateria: "Programacion I", codigoMateria: "SIS102", descripcion: "Introduccion a la programacion con enfoque en estructuras basicas de control y datos", creditos: 3, horasTeoricas: 3, horasPracticas: 2, profesor: "Ing. Sebastian Carrera", aula: "Lab 203", prerrequisitos: "Ninguno", promedioClasificacion: 4.7 },
  { nombreMateria: "Algebra Lineal", codigoMateria: "MAT102", descripcion: "Estudio de matrices determinantes vectores espacios vectoriales y sus aplicaciones", creditos: 3, horasTeoricas: 4, horasPracticas: 1, profesor: "Mg. Javier Villalba", aula: "Aula 102", prerrequisitos: "Calculo Diferencial", promedioClasificacion: 4.4 },
  { nombreMateria: "Fisica I", codigoMateria: "FIS101", descripcion: "Fundamentos de la mecanica clasica incluyendo cinematica y dinamica de particulas", creditos: 4, horasTeoricas: 3, horasPracticas: 3, profesor: "Dr. Sandra Rojas", aula: "Lab 105", prerrequisitos: "Ninguno", promedioClasificacion: 4.6 },
  { nombreMateria: "Quimica General", codigoMateria: "QUI101", descripcion: "Estudio de la estructura atomica enlaces quimicos y reacciones fundamentales", creditos: 3, horasTeoricas: 3, horasPracticas: 2, profesor: "Dr. Juan Torres", aula: "Lab 301", prerrequisitos: "Ninguno", promedioClasificacion: 4.3 },
  { nombreMateria: "Historia del Arte", codigoMateria: "HIS104", descripcion: "Introduccion a la evolucion del arte desde la antiguedad hasta la era moderna", creditos: 2, horasTeoricas: 2, horasPracticas: 0, profesor: "MG. Ana Gonzalez", aula: "Aula 304", prerrequisitos: "Ninguno", promedioClasificacion: 4.9 },
  { nombreMateria: "Etica Profesional", codigoMateria: "HUM201", descripcion: "Analisis de dilemas eticos en el contexto profesional y personal", creditos: 2, horasTeoricas: 2, horasPracticas: 0, profesor: "Dra. Maria Suarez", aula: "Aula 402", prerrequisitos: "Ninguno", promedioClasificacion: 4.8 },
  { nombreMateria: "Economia Basica", codigoMateria: "ECO101", descripcion: "Introduccion a los principios economicos fundamentales tanto micro como macro", creditos: 3, horasTeoricas: 3, horasPracticas: 1, profesor: "Dr. Pedro Gomez", aula: "Aula 503", prerrequisitos: "Ninguno", promedioClasificacion: 4.2 },
  { nombreMateria: "Programacion II", codigoMateria: "SIS202", descripcion: "Estructuras de datos avanzadas y principios de programacion orientada a objetos", creditos: 3, horasTeoricas: 3, horasPracticas: 2, profesor: "Ing. Andres Mendez", aula: "Lab 205", prerrequisitos: "Programacion I", promedioClasificacion: 4.5 },
  { nombreMateria: "Ecuaciones Diferenciales", codigoMateria: "MAT301", descripcion: "Solucion de ecuaciones diferenciales ordinarias y parciales", creditos: 3, horasTeoricas: 4, horasPracticas: 1, profesor: "Dr. Ricardo Ramirez", aula: "Aula 206", prerrequisitos: "Calculo Integral", promedioClasificacion: 4.7 },
  { nombreMateria: "Redes de Computadoras", codigoMateria: "SIS305", descripcion: "Principios de redes de computadoras topologias y protocolos", creditos: 4, horasTeoricas: 3, horasPracticas: 3, profesor: "Ing. Gabriel Pardo", aula: "Lab 202", prerrequisitos: "Ninguno", promedioClasificacion: 4.5 },
  { nombreMateria: "Fisica II", codigoMateria: "FIS202", descripcion: "Electromagnetismo circuitos y ondas", creditos: 4, horasTeoricas: 3, horasPracticas: 3, profesor: "Dra. Veronica Reyes", aula: "Lab 107", prerrequisitos: "Fisica I", promedioClasificacion: 4.4 },
  { nombreMateria: "Ingenieria de Software", codigoMateria: "SIS404", descripcion: "Metodologias de desarrollo de software desde el analisis hasta la implementacion", creditos: 4, horasTeoricas: 3, horasPracticas: 2, profesor: "Ing. Alberto Rivas", aula: "Lab 305", prerrequisitos: "Programacion II", promedioClasificacion: 4.8 },
  { nombreMateria: "Analisis Numerico", codigoMateria: "MAT401", descripcion: "Metodos numericos para la solucion de ecuaciones y problemas matematicos complejos", creditos: 3, horasTeoricas: 4, horasPracticas: 1, profesor: "Mg. Dany Cardenas", aula: "Aula 201", prerrequisitos: "Calculo Integral", promedioClasificacion: 4.3 },
 { nombreMateria: "Matematicas Discretas", codigoMateria: "MAT302", descripcion: "Estudio de estructuras matematicas discretas y sus aplicaciones", creditos: 3, horasTeoricas: 4, horasPracticas: 1, profesor: "Mg. Carlos Torres", aula: "Aula 103", prerrequisitos: "Algebra Lineal", promedioClasificacion: 4.5 },
  { nombreMateria: "Sistemas Operativos", codigoMateria: "SIS401", descripcion: "Fundamentos de sistemas operativos y su arquitectura", creditos: 4, horasTeoricas: 3, horasPracticas: 2, profesor: "Ing. Laura Torres", aula: "Lab 404", prerrequisitos: "Programacion II", promedioClasificacion: 4.6 },
  { nombreMateria: "Analisis de Algoritmos", codigoMateria: "SIS403", descripcion: "Estudio de algoritmos y su eficiencia", creditos: 3, horasTeoricas: 4, horasPracticas: 1, profesor: "Ing. David Morales", aula: "Aula 305", prerrequisitos: "Programacion I", promedioClasificacion: 4.4 },
  { nombreMateria: "Computacion Cuantica", codigoMateria: "SIS505", descripcion: "Introduccion a la computacion cuantica y sus principios", creditos: 4, horasTeoricas: 3, horasPracticas: 2, profesor: "Dra. Maria Velasco", aula: "Lab 301", prerrequisitos: "Ninguno", promedioClasificacion: 4.9 },
  { nombreMateria: "Desarrollo Web", codigoMateria: "SIS506", descripcion: "Principios y herramientas para el desarrollo de aplicaciones web", creditos: 4, horasTeoricas: 3, horasPracticas: 2, profesor: "Ing. Natalia Rios", aula: "Lab 204", prerrequisitos: "Programacion II", promedioClasificacion: 4.7 },
  { nombreMateria: "Estructuras de Datos", codigoMateria: "SIS203", descripcion: "Estudio de estructuras de datos y algoritmos", creditos: 3, horasTeoricas: 3, horasPracticas: 2, profesor: "Ing. Fernando Becerra", aula: "Lab 202", prerrequisitos: "Programacion I", promedioClasificacion: 4.5 }
]);
//db.materias.find({ nombreMateria: { $eq: "Python" } })
//db.materias.find({ creditos: { $gt: 3 } })
//db.materias.find({ horasTeoricas: { $gte: 4 } })

//db.materias.find({ horasPracticas: { $lt: 2 } })


//db.materias.find({ codigoMateria: { $lte: "MAT301" } })
//db.materias.find({ profesor: { $ne: "Ing. Mario Álvarez" } })

//db.materias.find({ aula: { $in: ["Lab 203", "Lab 205"] } })

//db.materias.find({ aula: { $nin: ["Aula 204", "Lab 305", "Lab 301"] } })

//db.materias.find({})

//db.materias.deleteOne({ nombreMateria: "Química Orgánica" })





